#!/bin/bash
# chkconfig: 2345 20 80
# description: MicroBlojeeq service

# Source function library.
. /etc/init.d/functions

user=_mblog
group=nginx
app_dir=/home/${user}
app_etc=/etc/mblog

start() {
    printf "Starting mblogd service...\n"
    exec ${app_dir}/env/bin/uwsgi --ini ${app_etc}/mblog-uwsgi.ini
}

stop() {
    printf "stopping\n"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        printf "dunno!\n"
        ;;
    *)
        "Usage: $0 {start|stop|status|restart}"
esac

exit 0
